// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArEkibpISm4B1XFt4f9ZXzFF-ccpVPG54',
    appId: '1:366202795388:web:6dc76ab9b33a47168de0f9',
    messagingSenderId: '366202795388',
    projectId: 'hain-kim',
    authDomain: 'hain-kim.firebaseapp.com',
    databaseURL:
        'https://hain-kim-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hain-kim.firebasestorage.app',
    measurementId: 'G-KJFSS1B2RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgVtvWUvjAre5q8yjR8EU83UGZPbx9aTI',
    appId: '1:366202795388:android:74c0181d183cc9c38de0f9',
    messagingSenderId: '366202795388',
    projectId: 'hain-kim',
    databaseURL:
        'https://hain-kim-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hain-kim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkBelFmkOr1AAgY3GoPYvRC8I-Hi36ER0',
    appId: '1:366202795388:ios:e21674bd9d920f5a8de0f9',
    messagingSenderId: '366202795388',
    projectId: 'hain-kim',
    databaseURL:
        'https://hain-kim-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hain-kim.firebasestorage.app',
    iosBundleId: 'com.example.hainkimoneylul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkBelFmkOr1AAgY3GoPYvRC8I-Hi36ER0',
    appId: '1:366202795388:ios:e21674bd9d920f5a8de0f9',
    messagingSenderId: '366202795388',
    projectId: 'hain-kim',
    databaseURL:
        'https://hain-kim-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hain-kim.firebasestorage.app',
    iosBundleId: 'com.example.hainkimoneylul',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArEkibpISm4B1XFt4f9ZXzFF-ccpVPG54',
    appId: '1:366202795388:web:c527f9700a69359b8de0f9',
    messagingSenderId: '366202795388',
    projectId: 'hain-kim',
    authDomain: 'hain-kim.firebaseapp.com',
    databaseURL:
        'https://hain-kim-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hain-kim.firebasestorage.app',
    measurementId: 'G-KLF44VGSL1',
  );
}
